app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function(){
	return redirect()->route('tasks.index');
});
Route::get('auth/login', ['as' => 'auth.index', 'middleware' => 'guest', 'uses' => 'SiteController@login']);
Route::post('auth/login', ['as' => 'auth.login', 'middleware' => 'guest', 'uses' => 'SiteController@signin']);
Route::get('auth/logout', ['as' => 'auth.logout', 'middleware' => 'auth', 'uses' => 'SiteController@logout']);
Route::get('auth/register', ['as' => 'auth.create', 'middleware' => 'guest', 'uses' => 'SiteController@register']);
Route::post('auth/register', ['as' => 'auth.register', 'middleware' => 'guest', 'uses' => 'SiteController@store']);

Route::resource('tasks', 'TaskController');
Route::get('tasks/getcrawl/{id?}', ['as' => 'tasks.download', 'uses' => 'TaskController@getTexts']);
Route::get('crawling/{id?}', ['as' => 'crawl.crawling', 'uses' => 'CrawlController@crawl']);

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Task;
use App\Model\UrlLog;
use App\Model\TextCrawl;

use Illuminate\Auth\Guard;

class TaskController extends Controller
{
    
    public function __construct() {
        $this->middleware('auth');
        \View::share('navTask', true);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Guard $auth)
    {
        $tasks = $auth->user()->tasks;
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $task = new Task();
        return view('tasks.create', compact('task'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Guard $auth, Request $request)
    {
        $task = new Task();
        if ($request->get('max_document') <= 0) {
            $request->merge(['max_document' => 500]);
        }
        $task->fill($request->all());
        $task->user_id = $auth->user()->id;
        $task->status = Task::STATUS_RUNNING;
        if ($task->save()) {
            $urlLog = new UrlLog();
            $urlLog->task_id = $task->id;
            $urlLog->url = $request->get('url_index_crawl');
            $urlLog->save();
            shell_exec("nohup php crawlprocess.php --url=".route('crawl.crawling', ['id' => $task->id])." >/dev/null 2>&1 &");
            return redirect()->route('tasks.index');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        if (!is_null($task)) {
            $task->delete();
        }
    }

    public function getTexts(Guard $auth, $taskId)
    {
        $task = Task::findOrFail($taskId);
        $texts = TextCrawl::where('task_id', $taskId)->take($task->max_document)->get();
        $title = "crawl/".$task->id."_".\Carbon\Carbon::now()->format('Y-m-d-His')."_texts.txt";
        foreach ($texts as $text) {
            file_put_contents($title, $text->text."\n", FILE_APPEND);
        }
        return response()->download($title)->deleteFileAfterSend(true);
    }
}

resources/views/tasks/create.blade.php
@extends('_layouts.default')

@section('title', 'Create Task')
@section('page-header-toolbar', 'Create Tasks')
@section('page-header')
  Tasks
@stop

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
          Create Task
      </div><!-- /.box-header -->
      <div class="box-body">
      @include('tasks.form', $task)
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>
@stop

resources/views/tasks/edit.blade.php
@extends('_layouts.default')

@section('title', 'Edit Task')
@section('page-header-toolbar', 'Edit Tasks')
@section('page-header')
  Tasks
@stop

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
          Edit Task
      </div><!-- /.box-header -->
      <div class="box-body">
      @include('tasks.form', $task)
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>
@stop

resources/views/tasks/form.blade.php
{!! Form::model($task, array('route' => ($task->exists ? array('tasks.update', $task->id) : array('tasks.store')), 'method' => ($task->exists ? 'PUT' : 'POST'))) !!}
<div class="form-group">
  <label for="inputEmail3" class="col-sm-3 control-label">Type Document Crawl</label>
  <div class="col-sm-9">
    {!! Form::select('type_document', array('Raw' => 'Raw', 'Article' => 'Article'), 'Raw'); !!}
  </div>
</div>
<br><br>
<div class="form-group">
  <label for="inputEmail3" class="col-sm-3 control-label">Max Document</label>
  <div class="col-sm-9">
    {!! Form::number('max_document', $task->max_document); !!}
  </div>
</div>
<br><br>
<div class="form-group">
  <label for="inputEmail3" class="col-sm-3 control-label">URL Index Crawling</label>
  <div class="col-sm-9">
    {!! Form::text('url_index_crawl', $task->url_index_crawl, ['class' => 'form-control', 'placeholder' => 'URL Article Crawl']); !!}
  </div>
</div>
<br><br><br>
<div class="form-group">
  <label for="inputEmail3" class="col-sm-3 control-label">URL Article Crawling</label>
  <div class="col-sm-9">
    {!! Form::text('url_article_crawl', $task->url_article_crawl, ['class' => 'form-control', 'placeholder' => 'URL Article Crawl']); !!}
  </div>
</div>
<br><br>
<div class="form-group">
  <label for="inputEmail3" class="col-sm-3 control-label">URL Pagination Crawling</label>
  <div class="col-sm-9">
    {!! Form::text('url_pagination_crawl', $task->url_pagination_crawl, ['class' => 'form-control', 'placeholder' => 'URL Pagination Crawl']); !!}
  </div>
</div>
<br><br>
<div class="form-group text-center">
  <button type="reset" class="btn btn-danger">Reset</button>
  @if($task->exists)
  <button type="submit" class="btn btn-success">Save</button>
  @else
  <button type="submit" class="btn btn-success">Create</button>
  @endif
</div>
{!! Form::close() !!}

resources/views/tasks/index.blade.php
@extends('_layouts.default')

@section('title', 'Task')
@section('page-header-toolbar', 'Tasks')
@section('page-header')
  Tasks
@stop

@section('content')
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
          <a href="{{ route('tasks.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> <span>Create</span></a>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="dataTables" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>Status</th>
              <th>Type</th>
              <th>Max</th>
              <th>URL Index Crawling</th>
              <th>URL Article Crawling</th>
              <th>URL Pagination Crawling</th>
              <th>Created At</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($tasks as $task)
            <tr>
              <td>{{ $task->id }}</td>
              <td>{{ $task->status }}</td>
              <td>{{ $task->type_document }}</td>
              <td>{{ $task->max_document }}</td>
              <td>{{ $task->url_index_crawl }}</td>
              <td>{{ $task->url_article_crawl }}</td>
              <td>{{ $task->url_pagination_crawl }}</td>
              <td>{{ $task->created_at }}</td>
              <td>
                @if ($task->status === $task::STATUS_RUNNING)
                <a href="{{ route('tasks.edit', $task) }}" class="btn btn-warning btn-sm btn-cell"><i class="fa fa-pause"></i> <span>Pause</span></a>
                @elseif ($task->status === $task::STATUS_STOP)
                <a href="{{ route('tasks.edit', $task) }}" class="btn btn-primary btn-sm btn-cell"><i class="fa fa-play"></i> <span>Play</span></a>
                @else
                <a href="{{ route('tasks.download', $task) }}" class="btn btn-success btn-sm btn-cell"><i class="fa fa-cloud-download"></i> <span>Download</span></a>
                @endif
                <!-- <a href="{{ route('tasks.edit', $task) }}" class="btn btn-success btn-sm btn-cell"><i class="fa fa-pencil"></i> <span>Edit</span></a> -->
                <a data-href="{{ route('tasks.destroy', $task) }}" class="btn btn-danger btn-sm btn-cell btn-delete" data-token="{{ csrf_token() }}"><i class="fa fa-trash"></i> <span>Delete</span></a>
              </td>
            </tr>
            @endforeach
          </tbody>
          <tfoot>
            <tr>
              <th>ID</th>
              <th>Status</th>
              <th>URL Crawling</th>
              <th>Created At</th>
              <th>Action</th>
            </tr>
          </tfoot>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div>
</div>
@stop